# Generated by Django 4.1.7 on 2023-04-17 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1_name', models.CharField(max_length=50, null=True)),
                ('company1_desig', models.CharField(max_length=50, null=True)),
                ('uompany1_duration', models.CharField(max_length=50, null=True)),
                ('company2_name', models.CharField(max_length=50, null=True)),
                ('company2_desig', models.CharField(max_length=50, null=True)),
                ('uompany2_duration', models.CharField(max_length=50, null=True)),
                ('company3_name', models.CharField(max_length=50, null=True)),
                ('company3_desig', models.CharField(max_length=50, null=True)),
                ('uompany3_duration', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
