# Generated by Django 4.1.7 on 2023-04-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employeeeducation_company1_desig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='uompany1_duration',
            new_name='company1_duration',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='uompany2_duration',
            new_name='company2_duration',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='uompany3_duration',
            new_name='company3_duration',
        ),
    ]
