# Generated by Django 4.1.7 on 2023-04-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_uompany1_duration_employeeexperience_company1_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='class_XI',
            new_name='class_X',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='yop_class_XI',
            new_name='yop_class_X',
        ),
    ]
